;; “≈ —“Œ¬€… ‘¿…À, œŒƒ Àﬁ◊¿≈Ã€… Õ¿ —“¿ƒ»» “–¿Õ—Àﬂ÷»»
;===============================================
;      OPIC.INC                               
;                                             
; INPUT CODING MESSAGE IN THE PORT A 8355 AND  
; OUTPUT DECOGING MESSAGE FROM THE PORT B 8355 
;===============================================
; SOURCE FILE WORK\L_01.A85
; INCLUDE FILE WORK\OPIS.MAC
;              WORK\LAB_IO.MAC
; OBJECT FILE  WORK\SUBR_01.OBJ
; INPUT FILE WORK\D441.MSG
; OUTPUT FILE WORK\D444.MSG - EMPTY
; COMAND FILE WORK\LAB_0.ZGR
;-----------------------------------------------

